#
#
#  C++ Portable Types Library (PTypes)
#  Version 1.8.3  Released 25-Aug-2003
#
#  Copyright (c) 2001, 2002, 2003 Hovik Melikyan
#
#  http://www.melikyan.com/ptypes/
#  http://ptypes.sourceforge.net/
#
#
#
# Makefile for FreeBSD, called from ../Makefile
#

CXX = g++

OS_CXXOPTS = -pthread
OS_LDLIBS = -lc_r

SOEXT = so
LIBTOOL = $(CXX) -shared -pthread
SOSTRIP = strip

include Makefile.common

