#
#
#  C++ Portable Types Library (PTypes)
#  Version 1.8.3  Released 25-Aug-2003
#
#  Copyright (c) 2001, 2002, 2003 Hovik Melikyan
#
#  http://www.melikyan.com/ptypes/
#  http://ptypes.sourceforge.net/
#
#
#
# Makefile for SunOS, called from ../Makefile
#

CXX = g++

OS_CXXOPTS = -D_REENTRANT
OS_LDLIBS = -lpthread -lsocket -lnsl -lposix4

OS_LDLIBS_ST = -lsocket -lnsl -lposix4

SOEXT = so
LIBTOOL = $(CXX) -shared
SOSTRIP = strip

include Makefile.common

