include(FindPkgMacros)
include(PreprocessorUtils)

set(PKG_NAME OGRE)
findpkg_begin(${PKG_NAME})

if (NOT ${PKG_NAME}_FOUND)
	find_path(${PKG_NAME}_INCLUDE_DIR NAMES Ogre.h PATH_SUFFIXES OGRE)
	find_library(${PKG_NAME}_LIBRARY  NAMES OgreMain libOgreMain)
	include_directories(${${PKG_NAME}_INCLUDE_DIR})
endif()

if (OGRE_INCLUDE_DIR)
	file(READ "${OGRE_INCLUDE_DIR}/OgrePrerequisites.h" OGRE_TEMP_VERSION_CONTENT)
	get_preprocessor_entry(OGRE_TEMP_VERSION_CONTENT OGRE_VERSION_MAJOR OGRE_VERSION_MAJOR)
	get_preprocessor_entry(OGRE_TEMP_VERSION_CONTENT OGRE_VERSION_MINOR OGRE_VERSION_MINOR)
	if (${OGRE_VERSION_MAJOR} EQUAL 1 AND ${OGRE_VERSION_MINOR} LESS 11)
		message(FATAL_ERROR "Required Ogre >= 1.11 or Ogre >= 2.1")
	elseif (${OGRE_VERSION_MAJOR} EQUAL 2 AND ${OGRE_VERSION_MINOR} LESS 1)
		message(FATAL_ERROR "Required Ogre >= 1.11 or Ogre >= 2.1")
	endif()
endif()
findpkg_finish(${PKG_NAME})
